name = input()
price = int(input())
weight = int(input())
money = int(input())
print("Чек")
print(str(name), "-", str(weight) + "кг -", str(price) + "руб/кг")
print("Итого:", str(price * weight) + "руб")
print("Внесено:", str(money) + "руб")
print("Сдача:", str(money - (price * weight)) + "руб")
